name: Unzip and Commit to Main

on:
  push:
    paths:
      - "*.zip" # Trigger the action when ZIP files are pushed

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }} # Checks out the active branch

      - name: Extract ZIP Files
        run: |
          for file in *.zip; do
            unzip -o "$file" -d ./ # Extract contents to the root directory
          done

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add .
          git commit -m "Add unzipped files"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} ${{ github.ref }}
